# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1018, 619)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        widget.setStyleSheet("")
        self.listWidget = QtWidgets.QListWidget(widget)
        self.listWidget.setGeometry(QtCore.QRect(0, 50, 151, 441))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayoutWidget = QtWidgets.QWidget(widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 40, 891, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.mainLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mainLayout.setContentsMargins(11, 11, 11, 11)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.layoutWidget = QtWidgets.QWidget(widget)
        self.layoutWidget.setGeometry(QtCore.QRect(-20, 490, 171, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.artimglabel = QtWidgets.QToolButton(self.layoutWidget)
        self.artimglabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.artimglabel.setStyleSheet("background-color:transparent")
        self.artimglabel.setText("")
        self.artimglabel.setIcon(icon)
        self.artimglabel.setIconSize(QtCore.QSize(63, 63))
        self.artimglabel.setCheckable(False)
        self.artimglabel.setObjectName("artimglabel")
        self.gridLayout.addWidget(self.artimglabel, 0, 1, 2, 1)
        self.songlabel = QtWidgets.QLabel(self.layoutWidget)
        self.songlabel.setText("")
        self.songlabel.setObjectName("songlabel")
        self.gridLayout.addWidget(self.songlabel, 0, 2, 1, 1)
        self.artlabel = QtWidgets.QLabel(self.layoutWidget)
        self.artlabel.setText("")
        self.artlabel.setObjectName("artlabel")
        self.gridLayout.addWidget(self.artlabel, 1, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(620, 0, 295, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.searchbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchbutton.setStyleSheet("background-color:transparent")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchbutton.setIcon(icon1)
        self.searchbutton.setObjectName("searchbutton")
        self.horizontalLayout.addWidget(self.searchbutton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pushButton_2.setStyleSheet("background-color:transparent")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pushButton_3.setStyleSheet("background-color:transparent")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/male.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.layoutWidget2 = QtWidgets.QWidget(widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 560, 1021, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevbutton = QtWidgets.QToolButton(self.layoutWidget2)
        self.prevbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prevbutton.setStyleSheet("background-color:transparent")
        self.prevbutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevbutton.setIcon(icon4)
        self.prevbutton.setIconSize(QtCore.QSize(30, 30))
        self.prevbutton.setObjectName("prevbutton")
        self.horizontalLayout_2.addWidget(self.prevbutton)
        self.playbutton = QtWidgets.QToolButton(self.layoutWidget2)
        self.playbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playbutton.setStyleSheet("background-color:transparent")
        self.playbutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playbutton.setIcon(icon5)
        self.playbutton.setIconSize(QtCore.QSize(40, 40))
        self.playbutton.setCheckable(True)
        self.playbutton.setObjectName("playbutton")
        self.horizontalLayout_2.addWidget(self.playbutton)
        self.nextbutton = QtWidgets.QToolButton(self.layoutWidget2)
        self.nextbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextbutton.setStyleSheet("background-color:transparent")
        self.nextbutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextbutton.setIcon(icon6)
        self.nextbutton.setIconSize(QtCore.QSize(30, 30))
        self.nextbutton.setObjectName("nextbutton")
        self.horizontalLayout_2.addWidget(self.nextbutton)
        self.nowtime = QtWidgets.QLabel(self.layoutWidget2)
        self.nowtime.setObjectName("nowtime")
        self.horizontalLayout_2.addWidget(self.nowtime)
        self.songslider = QtWidgets.QSlider(self.layoutWidget2)
        self.songslider.setMaximum(1)
        self.songslider.setSingleStep(0)
        self.songslider.setOrientation(QtCore.Qt.Horizontal)
        self.songslider.setObjectName("songslider")
        self.horizontalLayout_2.addWidget(self.songslider)
        self.endtime = QtWidgets.QLabel(self.layoutWidget2)
        self.endtime.setObjectName("endtime")
        self.horizontalLayout_2.addWidget(self.endtime)
        self.soundbutton = QtWidgets.QToolButton(self.layoutWidget2)
        self.soundbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.soundbutton.setStyleSheet("background-color:transparent")
        self.soundbutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/vol_medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.soundbutton.setIcon(icon7)
        self.soundbutton.setCheckable(True)
        self.soundbutton.setObjectName("soundbutton")
        self.horizontalLayout_2.addWidget(self.soundbutton)
        self.listbutton = QtWidgets.QToolButton(self.layoutWidget2)
        self.listbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listbutton.setStyleSheet("background-color:transparent")
        self.listbutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listbutton.setIcon(icon8)
        self.listbutton.setCheckable(True)
        self.listbutton.setObjectName("listbutton")
        self.horizontalLayout_2.addWidget(self.listbutton)
        self.songlistform = QtWidgets.QListWidget(widget)
        self.songlistform.setEnabled(True)
        self.songlistform.setGeometry(QtCore.QRect(775, 158, 231, 421))
        self.songlistform.setStyleSheet("")
        self.songlistform.setObjectName("songlistform")
        self.soundslider = QtWidgets.QSlider(widget)
        self.soundslider.setGeometry(QtCore.QRect(950, 520, 22, 59))
        self.soundslider.setMaximum(100)
        self.soundslider.setPageStep(0)
        self.soundslider.setProperty("value", 50)
        self.soundslider.setOrientation(QtCore.Qt.Vertical)
        self.soundslider.setObjectName("soundslider")

        self.retranslateUi(widget)
        self.searchbutton.clicked.connect(widget.search)
        self.pushButton_2.clicked.connect(widget.download)
        self.pushButton_3.clicked.connect(widget.player)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "MusicPlayer"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("widget", "播放列表"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.searchbutton.setText(_translate("widget", "搜索"))
        self.pushButton_2.setText(_translate("widget", "下载"))
        self.pushButton_3.setText(_translate("widget", "用户"))
        self.nowtime.setText(_translate("widget", "0:00"))
        self.endtime.setText(_translate("widget", "0:00"))

